### ISSUE TITLE
router-link on <a>

### ISSUE THREAD

**Issue by basvandenheuvel** [lrzeszotarski/angular2-in-5minutes#1]
Hi,

looking to your code in app.ts, i have similar code. The problem when i run is that i get an error saying:

Can't bind to 'routerLink' since it isn't a know property of the 'a' element and there are no matching directives with a corresponding property.

Did you have this problem? Thanks..

**Comment by lrzeszotarski** [comment]
Do you have router.dev.js (in my case https://github.com/lrzeszotarski/angular2-in-5minutes/blob/master/bower_components/angular2-build/router.dev.js) in your libs?

**Comment by basvandenheuvel** [comment]
Thanks for quick answer. I found the problem. I had "directives: [RouterOutlet]" were you have "directives: [RouterOutlet, RouterLink]". 

Now i do get another error. Ill keep comparing our code till it works haha. 

Thanks!

**Comment by lrzeszotarski** [comment]
Ok! Yes you have to be very explicit with Angular2. Cool that it works!

**Comment by basvandenheuvel** [comment]
Still not working. i have the following code: _______________________________________________________
//Reference stuff is here
import { Component, View, bootstrap } from 'angular2/angular2'
import { Location, RouteConfig, RouterLink, Router, RouterOutlet } from 'angular2/router';
import { routerInjectables, Pipeline } from 'angular2/router';
import { Directive, Attribute, ElementRef, DynamicComponentLoader} from 'angular2/angular2';

import {Home} from '../home/home';
import {Modal} from '../modal/modal';

@RouteConfig([
    { path: '/', component: Home, as: 'home' },
    { path: '/modal', component: Modal, as: 'modal' }
])
@Component({
    selector: 'my-app'
})
@View({
    directives: [
        RouterOutlet,
        RouterLink
    ],
    template: `
        <nav>
          <ul>
            <li><a [router-link]=['/home']>Home</a></li>
            <li><a [router-link]=['/modal']>Modal (bootstrap)</a></li>
          </ul>
        </nav>
        <main>
          <router-outlet></router-outlet>
        </main>
      `
})
class AppComponent {
}

bootstrap(AppComponent, [routerInjectables]);
_______________________________________________________

Once i open in my browser i get a big error saying: 

TypeError: Cannot read property 'startsWith' of null
STACKTRACE:
TypeError: Cannot read property 'startsWith' of null
    at execute.Location.normalizeAbsolutely (https://code.angularjs.org/2.0.0-alpha.28/router.dev.js:475:19)

With loads more errors following in the same message. I see terms like " changeDetector" and "LifeCycle"  and "DetectChanges". Not sure where error comes from since our code is pretty much the same.

**Comment by basvandenheuvel** [comment]
![error](https://cloud.githubusercontent.com/assets/3515248/9492727/8a8d252c-4bfa-11e5-8408-f7489971e990.png)

Thats the error i get..

**Comment by lrzeszotarski** [comment]
Do you have the same error for https://code.angularjs.org/2.0.0-alpha.33/router.dev.js

**Comment by basvandenheuvel** [comment]
Remark:

When i click on my "Home button"  i get the error over and over again saying: " TypeError: Cannot read property 'length' of undefined ".

When i click on my "Modal button"  i get the error ove rand over again saying: " TypeError: Cannot read property 'length' of null "

Difference is undefined and null.....

**Comment by basvandenheuvel** [comment]
That fixed it! i had the 2.0.0-alpha.28.....

**Comment by basvandenheuvel** [comment]
Thank you so much.

To bad the documentation about NG2 is still pretty #@!*#&@ up.

**Comment by lrzeszotarski** [comment]
True but a lot of things is still changing in the api, so we are 'Angular2 pioniers' :)

**Comment by basvandenheuvel** [comment]
Thank you for the help! I keep an eye on you for you might post more NG2 project in the future!
