### ISSUE TITLE
Refresh / manually navigation problem

### ISSUE THREAD

**Issue by basvandenheuvel** [lrzeszotarski/angular2-in-5minutes#2]
Sorry there i am again.

The navigation does work right now, i have two buttons and when i click on the other one it shows the other content and the url changes from "localhost/home"  to "localhost/modal".

But im wondering if you have the same issue i have, once i press F5 or manually type " localhost/modal"  when im on the home page i get an error that the page is not found....... 

My routeConfig looks like:

```javascript
@RouteConfig([
    { path: '/', redirectTo: '/home' },
    { path: '/home', component: Home, as: 'home' },
    { path: '/modal', component: Modal, as: 'modal' }
])
```

**Comment by basvandenheuvel** [comment]
So my URL looks like this when i start up  my site:

http://localhost:49628/home

because i have the redirectTo... if i press F5 i get an 404 error

**Comment by basvandenheuvel** [comment]
![error](https://cloud.githubusercontent.com/assets/3515248/9493283/db59c0ce-4bfe-11e5-9604-46302726b0ff.png)


thats how the error looks like when i open it in wamp (everything works fine) and i press F5

**Comment by lrzeszotarski** [comment]
see http://stackoverflow.com/questions/20104772/refreshf5-ngview-with-angularjs
